"""add analytics table

Revision ID: 8f89cb293cba
Revises: 1fc05da58a8c
Create Date: 2026-06-07 23:17:40.575569

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8f89cb293cba'
down_revision: Union[str, Sequence[str], None] = '1fc05da58a8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_analytics_summary',
    sa.Column('url_id', sa.Integer(), nullable=False),
    sa.Column('total_clicks', sa.Integer(), nullable=False),
    sa.Column('unique_clicks', sa.Integer(), nullable=False),
    sa.Column('last_clicked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], name=op.f('fk_url_analytics_summary_url_id_urls'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('url_id', name=op.f('pk_url_analytics_summary'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url_analytics_summary')
    # ### end Alembic commands ###
