"""add_qr_code_to_urls

Revision ID: 93162d97eb99
Revises: 8f89cb293cba
Create Date: 2026-06-07 23:42:42.779953

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '93162d97eb99'
down_revision: Union[str, Sequence[str], None] = '8f89cb293cba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('qr_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'qr_code')
    # ### end Alembic commands ###
