"""add_webhook_received_events_table

Revision ID: e73f214a9451
Revises: c3d4e5f6a7b8
Create Date: 2026-06-13 15:36:37.083189

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e73f214a9451'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_received_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('webhook_id', sa.Integer(), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('headers', sa.Text(), nullable=True),
    sa.Column('signature', sa.String(), nullable=True),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('source_ip', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhooks.id'], name=op.f('fk_webhook_received_events_webhook_id_webhooks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_webhook_received_events_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_received_events'))
    )
    op.create_index(op.f('ix_webhook_received_events_id'), 'webhook_received_events', ['id'], unique=False)
    op.drop_constraint(op.f('uq_favorites_user_id_url_id'), 'favorites', type_='unique')
    op.create_unique_constraint('uq_favorite_user_url', 'favorites', ['user_id', 'url_id'])
    op.create_unique_constraint('uq_tag_name_workspace', 'tags', ['name', 'workspace_id'])
    op.drop_constraint(op.f('uq_users_google_id'), 'users', type_='unique')
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.drop_constraint(op.f('uq_workspace_members_workspace_id_user_id'), 'workspace_members', type_='unique')
    op.create_unique_constraint('uq_workspace_member', 'workspace_members', ['workspace_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_workspace_member', 'workspace_members', type_='unique')
    op.create_unique_constraint(op.f('uq_workspace_members_workspace_id_user_id'), 'workspace_members', ['workspace_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.create_unique_constraint(op.f('uq_users_google_id'), 'users', ['google_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_tag_name_workspace', 'tags', type_='unique')
    op.drop_constraint('uq_favorite_user_url', 'favorites', type_='unique')
    op.create_unique_constraint(op.f('uq_favorites_user_id_url_id'), 'favorites', ['user_id', 'url_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_webhook_received_events_id'), table_name='webhook_received_events')
    op.drop_table('webhook_received_events')
    # ### end Alembic commands ###
