"""timezone_aware_audit_created_at

Revision ID: fa956e5f83aa
Revises: e73f214a9451
Create Date: 2026-06-13 18:00:15.648182

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'fa956e5f83aa'
down_revision: Union[str, Sequence[str], None] = 'e73f214a9451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
